version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - ./portainer/Portainer-CN:/public
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - portainer

networks:
  portainer:
    external: true